/* Autogenerated file. Do not edit manually. */
/* eslint-disable */

import { Contract, Signer } from 'ethers';
import { Provider } from '@ethersproject/providers';

import type { I0xLendingIncentivesController } from './I0xLendingIncentivesController';

export class I0xLendingIncentivesController__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider,
  ): I0xLendingIncentivesController {
    return new Contract(
      address,
      _abi,
      signerOrProvider,
    ) as I0xLendingIncentivesController;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: 'address[]',
        name: 'assets',
        type: 'address[]',
      },
      {
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
      {
        internalType: 'address',
        name: 'to',
        type: 'address',
      },
    ],
    name: 'claimRewards',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];
